import {
  Archive,
  ArchiveRestore,
  ArrowDown,
  ArrowRightLeft,
  ArrowUp,
  ArrowUpDown,
  ArrowUpRight,
  BadgeCheck,
  Ban,
  Bell,
  BellRing,
  BookOpenCheck,
  BriefcaseBusiness,
  Building2,
  CalendarDays,
  ChartColumn,
  ChartPie,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleCheck,
  CircleUser,
  CircleX,
  Clock,
  Coins,
  Columns3,
  Ellipsis,
  Eye,
  FileText,
  Files,
  Gauge,
  Gift,
  Globe,
  Handshake,
  Heart,
  History,
  House,
  Image,
  Inbox,
  Info,
  KeyRound,
  Landmark,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  LayoutList,
  Link2,
  ListChecks,
  ListFilter,
  ListTree,
  Lock,
  LockOpen,
  LogOut,
  Menu,
  MessageCircle,
  MessageSquare,
  MonitorCog,
  Moon,
  Paperclip,
  Pencil,
  Percent,
  Plus,
  ReceiptText,
  RefreshCw,
  Repeat,
  RotateCcw,
  ScanFace,
  Search,
  Send,
  Settings,
  ShieldAlert,
  ShieldCheck,
  SlidersHorizontal,
  Smartphone,
  Square,
  SquareCheckBig,
  Sun,
  SunMoon,
  Table2,
  Tags,
  Ticket,
  Trash2,
  TrendingUp,
  TriangleAlert,
  Trophy,
  Undo2,
  UserCheck,
  UserCog,
  Users,
  Wallet,
  WifiOff,
  X,
  type LucideIcon,
} from 'lucide-react-native'

import { iconSize, iconStroke, type AppColors } from '@/theme/tokens'
import { useAppColors } from '@/theme/use-theme'

/**
 * Дүрсний ганц эх сурвалж — lucide, вэб админтай ижил сан. Дуудагч нь
 * lucide-ийн нэрийг мэдэхгүй: `<AppIcon name="leave" />`. Бүх санг биш,
 * энд нэрлэсэн дүрсийг л импортолж bundle-ыг жижиг байлгана.
 */
const ICONS = {
  menu: Menu,
  close: X,
  back: ChevronLeft,
  forward: ChevronRight,
  expand: ChevronDown,
  collapse: ChevronUp,
  search: Search,
  refresh: RefreshCw,
  add: Plus,
  check: Check,
  checkCircle: CircleCheck,
  cancel: CircleX,
  warning: TriangleAlert,
  info: Info,
  filter: ListFilter,
  more: Ellipsis,
  external: ArrowUpRight,
  signOut: LogOut,
  settings: Settings,
  themeDark: Moon,
  themeLight: Sun,
  themeAuto: SunMoon,
  lock: Lock,
  unlock: LockOpen,
  key: KeyRound,
  biometric: ScanFace,
  bell: Bell,
  clock: Clock,
  offline: WifiOff,
  retry: RotateCcw,
  refund: Undo2,
  edit: Pencil,
  trash: Trash2,
  archive: Archive,
  unarchive: ArchiveRestore,
  checkbox: Square,
  checkboxChecked: SquareCheckBig,
  attachment: Paperclip,
  comment: MessageCircle,
  checklist: ListChecks,
  cards: LayoutList,
  table: Table2,
  columns: Columns3,
  sort: ArrowUpDown,
  sortAsc: ArrowUp,
  sortDesc: ArrowDown,
  view: Eye,

  home: House,
  modules: LayoutGrid,
  work: BriefcaseBusiness,
  profile: CircleUser,

  dashboard: LayoutDashboard,
  users: Users,
  admin: UserCog,
  kyc: BadgeCheck,
  shield: ShieldCheck,
  wallet: Wallet,
  bank: Landmark,
  transfer: ArrowRightLeft,
  transaction: ReceiptText,
  convert: Repeat,
  crypto: Coins,
  trading: TrendingUp,
  stake: ChartPie,
  reward: Gift,
  news: FileText,
  mobile: Smartphone,
  push: BellRing,
  support: Heart,
  ticket: Ticket,
  chat: MessageSquare,
  compliance: ShieldAlert,
  monitor: MonitorCog,
  config: SlidersHorizontal,
  globe: Globe,
  history: History,
  block: Ban,
  send: Send,
  leave: CalendarDays,
  takeAction: BookOpenCheck,
  inbox: Inbox,
  folder: Layers,
  partner: Handshake,
  chart: ChartColumn,
  link: Link2,
  image: Image,
  files: Files,
  tree: ListTree,
  tags: Tags,
  trophy: Trophy,
  userCheck: UserCheck,
  gauge: Gauge,
  percent: Percent,
  building: Building2,
} satisfies Record<string, LucideIcon>

export type AppIconName = keyof typeof ICONS

/**
 * Дүрс үргэлж өнгөгүй — цагаан (`default`), саарал (`muted`), эсвэл
 * primary товч дээр (`inverse`). Статусын өнгө дүрсэнд биш, pill/текстэд.
 */
export type IconTone = 'default' | 'muted' | 'inverse'

export type AppIconProps = {
  name: AppIconName
  size?: number
  tone?: IconTone
}

function toneColors(colors: AppColors): Record<IconTone, string> {
  return {
    default: colors.foreground,
    muted: colors.mutedForeground,
    inverse: colors.primaryForeground,
  }
}

export function AppIcon({
  name,
  size = iconSize.md,
  tone = 'default',
}: AppIconProps) {
  const { colors } = useAppColors()
  const Glyph = ICONS[name]

  return (
    <Glyph
      size={size}
      color={toneColors(colors)[tone]}
      strokeWidth={iconStroke}
    />
  )
}
